FROM nginx:alpine

# Copiar certificados SSL
COPY certificates/barbearia.crt /etc/nginx/certificates/
COPY certificates/barbearia.key /etc/nginx/certificates/

# Copiar configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expor portas
EXPOSE 80
EXPOSE 443 